language: python

python:
  - "3.6"

before_script:
  - source .env

script:
  - pytest tests/

# this only works on gitlab-ci
#run_job:
#  script:
#    - python hello.py
#
#test_job:
#  script:
#    - pytest tests/
